gen_model:
  model_name: gpt2-large-finetuned
  apply_model_parallel: True
  tokenizer:
    model_name: gpt2-large-finetuned
    padding_side: left
    truncation_side: left
    pad_token_as_eos_token: True
  generation_kwargs:
    do_sample: False
    min_new_tokens: 1
    max_new_tokens: 50

reward_fn:
  id: bert
  args:
    threshold: 0.70
    lamb: -0.01
    bert_type: f1

datapool:
  id: alpaca_plus
  args:
    num_tokens_to_predict: 50

env:
  n_envs: 8
  obs_space: FixedTokenObservation
  act_space: BatchFixedTokenAction
  args:
    max_prompt_length: 128
    max_episode_length: 1
    terminate_on_eos: True

alg:
  id: pg_mask
  args:
    sample_k: 4
    use_scst: true
    n_steps: 1
    gae_lambda: 1
    gamma: 1
    batch_size: 32
    verbose: 1
    learning_rate: 0.00003
    normalize_advantage: false
    ent_coef: 0.001

  policy:
    id: BatchTokenPolicy
    args:
      model_name: distilroberta-base
      lr_scheduler:

train_evaluation:
  eval_batch_size: 32
  n_iters: 10000
  save_every: 1
  eval_freq: 100000000 # deprecated
  generation_kwargs:
    do_sample: False
    min_new_tokens: 1
    max_new_tokens: 50
